feat(github): implement release please for releasing part - #65
Signed-off-by: kilianpaquier <kilian@kilianpaquier.com>

diff --git a/pkg/generate/templates/.github/actions/version/action.yml.tmpl b/pkg/generate/templates/.github/actions/version/action.yml.tmpl
--- a/pkg/generate/templates/.github/actions/version/action.yml.tmpl
+++ b/pkg/generate/templates/.github/actions/version/action.yml.tmpl
@@ -9,13 +9,18 @@ description: Compute the next release version or release it
 
 <<- $gobuild := and $golang (gt (len .Clis) 0) (not .NoGoreleaser) >>
 
+<<- if .CI.Release >>
+
 inputs:
   download_dist:
     description: Whether to build artifact into dist folder or not
     default: "false"
-  dry_run:
-    description: Dry run
-    default: "true"
+  mode:
+    description: |
+      Action mode:
+        - "dry_run" to only get the next version number
+        - "draft" to get the next version number and create draft pull requests and releases
+        - "release" to get the next version number and create pull requests, tags and releases
   token:
     description: Github access token
     required: true
@@ -24,20 +29,34 @@ inputs:
     description: Access token for the npm registry
     required: true
 <<- end >>
+<<- end >>
+
 outputs:
-  branch_sha: 
+  branch_sha:
     description: The concerned branch sha256 value
     value: ${{ steps.version.outputs.branch_sha }}
   release:
     description: Whether a release can be made or not
     value: ${{ steps.version.outputs.release }}
-  version: 
+  version:
     description: The computed version
     value: ${{ steps.version.outputs.version }}
 
 runs:
   using: composite
   steps:
+    - shell: bash
+      run: |
+        if [ "${MODE}" != "dry_run" ] && [ "${MODE}" != "draft" ] && [ "${MODE}" != "release" ]; then
+          echo "invalid input mode '${MODE}', must be one of 'dry_run', 'draft', 'release'"
+          exit 2
+        fi
+
+        if [ "${MODE}" != "dry_run" ] && [ "${GITHUB_REF_PROTECTED}" != "true" ]; then
+          echo "invalid input mode '${MODE}', can't be 'draft' or 'release' when github branch isn't protected"
+        fi
+      env:
+        MODE: ${{ inputs.mode }}
 
 <<- /* *********************************************************************************************** */ ->>
 <<- /* *********************************************************************************************** */ ->>
@@ -83,9 +102,6 @@ runs:
     - id: release_check
       shell: bash
       run: |
-        BRANCH_SHA=$(echo "${GITHUB_REF_NAME}" | sha256sum | cut -c -8)
-        echo "branch_sha=${BRANCH_SHA}" >> $GITHUB_OUTPUT
-
         if [ "${GITHUB_REF_NAME}" = "main" ] || [ "${GITHUB_REF_NAME}" = "master" ]; then
           echo "release=true" >> $GITHUB_OUTPUT
         else
@@ -95,7 +111,7 @@ runs:
     - id: gh_release
       uses: softprops/action-gh-release@v2
       with:
-        draft: ${{ inputs.dry_run != 'false' }}
+        draft: ${{ inputs.mode != 'release' }}
         files: |
           CHANGELOG.md
 <<- if $gobuild >>
@@ -107,7 +123,7 @@ runs:
         target_commitish: ${{ github.ref_name }}
         token: ${{ inputs.token }}
     - uses: actions/github-scripts@v7
-      if: ${{ inputs.dry_run != 'false' }} # delete release in case of dry_run since we only desired the next version number
+      if: ${{ inputs.mode == 'dry_run' }} # delete release in case of dry_run since we only desired the next version number
       with:
         script: |
           github.rest.repos.deleteRelease({
@@ -118,11 +134,12 @@ runs:
     - id: version
       shell: bash
       run: |
+        BRANCH_SHA=$(echo "${GITHUB_REF_NAME}" | sha256sum | cut -c -8)
         echo "branch_sha=${BRANCH_SHA}" >> $GITHUB_OUTPUT
+
         echo "release=${RELEASE}" >> $GITHUB_OUTPUT
         echo "version=${RELEASE_URL##*/}" >> $GITHUB_OUTPUT # remove everything before the last / in the URL (should more or less match the tag name ...)
       env:
-        BRANCH_SHA: ${{ steps.release_check.outputs.branch_sha }}
         RELEASE_URL: ${{ steps.gh_release.outputs.url }}
         RELEASE: ${{ steps.release_check.outputs.release }}
     - shell: bash
@@ -179,7 +196,7 @@ runs:
         name: v$RESOLVED_VERSION
         prerelease-identifier: ${{ steps.release_check.outputs.identifier }}
         prerelease: ${{ steps.release_check.outputs.release != 'true' }}
-        publish: ${{ inputs.dry_run == 'false' }}
+        publish: ${{ inputs.mode == 'release' }}
         tag: v$RESOLVED_VERSION
       env:
         GITHUB_TOKEN: ${{ inputs.token }}
@@ -193,10 +210,11 @@ runs:
         VERSION: ${{ steps.drafter.outputs.tag_name }}
         RELEASE: ${{ steps.release_check.outputs.release }}
         BRANCH_SHA: ${{ steps.release_check.outputs.branch_sha }}
+    # https://github.com/marketplace/actions/gh-release
     - uses: softprops/action-gh-release@v2
-      if: ${{ inputs.dry_run == 'false' }}
+      if: ${{ inputs.mode != 'dry_run' }} # only upload assets when it's draft mode or release mode
       with:
-        draft: false # run is not in dry_run mode
+        draft: ${{ inputs.mode != 'release' }}
         files: |
           CHANGELOG.md
 <<- if $gobuild >>
@@ -209,7 +227,7 @@ runs:
         target_commitish: ${{ github.ref_name }}
         token: ${{ inputs.token }}
     - uses: actions/github-scripts@v7
-      if: ${{ inputs.dry_run != 'false' }} # delete release in case of dry_run since we only desired the next version number
+      if: ${{ inputs.mode == 'dry_run' }} # delete release in case of dry_run since we only desired the next version number
       with:
         script: |
           github.rest.repos.deleteRelease({
@@ -221,6 +239,89 @@ runs:
       run: echo $VERSION
       env:
         VERSION: ${{ steps.version.outputs.version }}
+<<- end >>
+
+<<- /* *********************************************************************************************** */ ->>
+<<- /* *********************************************************************************************** */ ->>
+<<- /* *********************************************************************************************** */ ->>
+<<- /* *********************************************************************************************** */ ->>
+
+<<- if .IsReleaseAction "release-please" >>
+<<- /* retrieve dist for go binaries and nodejs dist folder (uploaded with semantic-release to npm registry) */>>
+<<- if or $gobuild $nodejs >>
+    - uses: actions/download-artifact@v4
+      if: ${{ inputs.download_dist == 'true' }}
+      with:
+        name: build
+        path: dist
+<<- end >>
+    - id: release_check
+      shell: bash
+      run: |
+        BRANCH_SHA=$(echo "${GITHUB_REF_NAME}" | sha256sum | cut -c -8)
+        echo "branch_sha=${BRANCH_SHA}" >> $GITHUB_OUTPUT
+
+        case "${GITHUB_REF_NAME}" in
+          main|master)
+            echo "release=true" >> $GITHUB_OUTPUT
+            ;;
+          beta|staging)
+            echo "release=false" >> $GITHUB_OUTPUT
+            echo "identifier=beta" >> $GITHUB_OUTPUT
+            ;;
+          alpha|dev|develop|development)
+            echo "release=false" >> $GITHUB_OUTPUT
+            echo "identifier=alpha" >> $GITHUB_OUTPUT
+            ;;
+          next)
+            echo "release=false" >> $GITHUB_OUTPUT
+            echo "identifier=next" >> $GITHUB_OUTPUT
+            ;;
+        esac
+    - shell: bash
+      run: |
+        envsubst < .github/release-please.config.jsonc > .github/release-please.envsubst.config.jsonc
+        mv .github/release-please.envsubst.config.jsonc .github/release-please.config.jsonc
+      env:
+        DRAFT: ${{ inputs.mode != 'release' }}
+        PRERELEASE: ${{ steps.release_check.outputs.release != 'true' }}
+        PRERELEASE_IDENTIFIER: ${{ steps.release_check.outputs.identifier }}
+    # https://github.com/marketplace/actions/release-please-action
+    - id: release_please
+      uses: googleapis/release-please-action@v4
+      with:
+        config-file: .github/release-please.config.jsonc
+        manifest-file: .github/release-please.manifest.jsonc
+        skip-github-pull-request: ${{ inputs.mode == 'dry_run' }} # don't create pull request in dry run mode
+        skip-github-release: ${{ inputs.mode == 'dry_run' }} # don't create release in dry run mode
+        target-branch: ${{ github.ref_name }}
+        token: ${{ inputs.token }}
+    - id: version
+      shell: bash
+      run: |
+        echo "branch_sha=${BRANCH_SHA}" >> $GITHUB_OUTPUT
+        echo "release=${RELEASE}" >> $GITHUB_OUTPUT
+        echo "version=${VERSION}" >> $GITHUB_OUTPUT
+      env:
+        VERSION: ${{ steps.release_please.outputs.tag_name }}
+        RELEASE: ${{ steps.release_check.outputs.release }}
+        BRANCH_SHA: ${{ steps.release_check.outputs.branch_sha }}
+    # https://github.com/marketplace/actions/gh-release
+    - uses: softprops/action-gh-release@v2
+      if: ${{ inputs.mode != 'dry_run' }} # only upload assets when it's draft mode or release mode
+      with:
+        draft: ${{ inputs.mode != 'release' }}
+        files: |
+          CHANGELOG.md
+<<- if $gobuild >>
+          checksums.txt
+          dist/*
+<<- end >>
+        generate_release_notes: false
+        prerelease: ${{ steps.version.outputs.release != 'true' }}
+        tag_name: ${{ steps.release_please.outputs.tag_name }}
+        target_commitish: ${{ github.ref_name }}
+        token: ${{ inputs.token }}
 <<- end >>
 
 <<- /* *********************************************************************************************** */ ->>
@@ -260,18 +361,7 @@ runs:
 <<- if .CI.Release.Backmerge >>
           @kilianpaquier/semantic-release-backmerge
 <<- end >>
-        dry_run: ${{ inputs.dry_run != 'false' }}
-        tag_format: v${version}
-        branches: |
-          [
-            "(master|main)",
-            "v+([0-9])?(.{+([0-9]),x}).x",
-            { "name": "next", "prerelease": true },
-            { "name": "beta", "prerelease": true },
-            { "name": "alpha", "prerelease": true },
-            { "name": "staging", "prerelease": "beta" },
-            { "name": "(dev|develop|development)", "prerelease": "alpha" }
-          ]
+        dry_run: ${{ inputs.mode != 'release' }} # semantic-release doesn't handle draft mode since with dry_run as false mode will at least create and push the tag
       env:
         GITHUB_TOKEN: ${{ inputs.token }}
 <<- if $nodejs >>
@@ -285,9 +375,9 @@ runs:
         BRANCH_SHA=$(echo "${GITHUB_REF_NAME}" | sha256sum | cut -c -8)
         echo "branch_sha=${BRANCH_SHA}" >> $GITHUB_OUTPUT
 
-        if echo "$SEMREL_INFO_NEXT_VERSION" | grep -Eq "^[0-9]+(\.[0-9]+){2}.*$"; then
-          echo "version=v$SEMREL_INFO_NEXT_VERSION" >> $GITHUB_OUTPUT
-          if echo "$SEMREL_INFO_NEXT_VERSION" | grep -Eq "^[0-9]+(\.[0-9]+){2}$"; then
+        if echo "${SEMREL_INFO_NEXT_VERSION}" | grep -Eq "^[0-9]+(\.[0-9]+){2}.*$"; then
+          echo "version=v${SEMREL_INFO_NEXT_VERSION}" >> $GITHUB_OUTPUT
+          if echo "${SEMREL_INFO_NEXT_VERSION}" | grep -Eq "^[0-9]+(\.[0-9]+){2}$"; then
             echo "release=true" >> $GITHUB_OUTPUT
           else
             echo "release=false" >> $GITHUB_OUTPUT
